name: ocean_guard
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  iconsax: ^0.0.8
  email_validator: ^2.1.17
  image_picker: ^1.0.5
  cupertino_icons: ^1.0.2
  flutter_map: ^6.1.0
  location: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: 'launcher_icon'
  image_path: 'assets/icons/icon.jfif'

flutter:
  uses-material-design: true
  assets:
    - assets/images/world-map.gif
    - assets/images/dirty-ocean.jpg
    - assets/images/ishaan.jfif